"""合并本体渲染工具实现。

作用：
- 将 `merge_ontology_classes` 产出的 merged class 元数据渲染为 Python 本体文件和 Markdown 对齐报告。
- 自动补充必要 import、class docstring、source 信息、字段注释，并可对生成 Python 文件执行 `py_compile`。

主要输入：
- `merged_classes_json`: 合并后的 JSON，可为 `merge_ontology_classes` 输出或 merged class 列表。
- `output_dir`: 输出目录。
- `python_filename`: Python 本体文件名，默认 `merged_ontology.py`。
- `report_filename`: Markdown 报告文件名，默认 `alignment_report.md`。
- `compile_check`: 是否对渲染出的 Python 文件执行编译检查。

主要输出：
- JSON/dict，包含 `python_file`、`report_file`、`class_count`、`conflict_count` 和 `compile_result`。
"""

from __future__ import annotations

import json
import py_compile
from pathlib import Path
from typing import Any

from .paths import ensure_output_dir, resolve_path


def _load_merged_classes(merged_classes_json: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    data = json.loads(merged_classes_json)
    if isinstance(data, dict):
        classes = data.get("merged_classes", data.get("classes", []))
        conflicts = data.get("conflicts", [])
    else:
        classes = data
        conflicts = []
    if not isinstance(classes, list):
        raise ValueError("merged_classes_json must contain a list or object with `merged_classes`.")
    return [item for item in classes if isinstance(item, dict)], [item for item in conflicts if isinstance(item, dict)]


def _collect_imports(classes: list[dict[str, Any]]) -> list[str]:
    imports: set[str] = set()
    for cls in classes:
        decorators = set(cls.get("decorators", []) or [])
        if "dataclass" in decorators:
            imports.add("from dataclasses import dataclass")
        bases = cls.get("bases", []) or []
        if any("BaseModel" in str(base) for base in bases):
            imports.add("from pydantic import BaseModel, Field")
        for field in cls.get("fields", []) or []:
            field_type = str(field.get("type") or "")
            typing_names = [name for name in ("Any", "Dict", "List", "Optional", "Protocol") if name in field_type]
            if typing_names:
                imports.add(f"from typing import {', '.join(sorted(set(typing_names)))}")
    return sorted(imports)


def _render_field(field: dict[str, Any]) -> str:
    name = str(field.get("name") or "field")
    field_type = str(field.get("type") or "Any")
    default = field.get("default")
    comment = str(field.get("comment") or "").replace("\n", " ")
    line = f"{name}: {field_type}"
    if default is not None:
        line += f" = {default}"
    if comment:
        line += f"  # {comment}"
    return line


def _render_class(cls: dict[str, Any]) -> str:
    lines: list[str] = []
    for decorator in cls.get("decorators", []) or []:
        lines.append(f"@{decorator}")
    class_name = str(cls.get("class_name") or "MergedOntology")
    bases = [str(base) for base in cls.get("bases", []) or [] if str(base)]
    lines.append(f"class {class_name}({', '.join(bases)}):" if bases else f"class {class_name}:")
    doc = str(cls.get("docstring") or "").strip()
    if doc:
        lines.append('    """')
        for doc_line in doc.splitlines():
            lines.append(f"    {doc_line}")
        lines.append('    """')
    source_files = cls.get("source_files") or ([cls.get("source_file")] if cls.get("source_file") else [])
    if source_files:
        lines.append(f"    # Source files: {', '.join(str(item) for item in source_files)}")
    original_names = cls.get("original_names", []) or []
    if len(original_names) > 1:
        lines.append(f"    # Original names: {', '.join(str(item) for item in original_names)}")
    fields = cls.get("fields", []) or []
    if not fields:
        lines.append("    pass")
    else:
        for field in fields:
            if isinstance(field, dict):
                lines.append(f"    {_render_field(field)}")
    return "\n".join(lines)


def render_python(classes: list[dict[str, Any]]) -> str:
    lines = [
        '"""',
        "Merged ontology classes.",
        "Auto-generated by render_merged_ontology.",
        '"""',
        "",
    ]
    imports = _collect_imports(classes)
    if imports:
        lines.extend(imports)
        lines.append("")
    for cls in classes:
        lines.append(_render_class(cls))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_report(classes: list[dict[str, Any]], conflicts: list[dict[str, Any]]) -> str:
    lines = [
        "# Ontology Alignment Report",
        "",
        "## Summary",
        "",
        f"- Total rendered classes: {len(classes)}",
        f"- Field conflicts: {len(conflicts)}",
        "",
        "## Classes",
        "",
        "| Class | Source files | Fields |",
        "|---|---:|---:|",
    ]
    for cls in classes:
        source_files = cls.get("source_files") or ([cls.get("source_file")] if cls.get("source_file") else [])
        lines.append(
            f"| {cls.get('class_name', '')} | {len(source_files)} | {len(cls.get('fields', []) or [])} |"
        )
    if conflicts:
        lines.extend(["", "## Field Conflicts", ""])
        for conflict in conflicts:
            lines.append(f"- `{conflict.get('field_name')}`: {len(conflict.get('variants', []) or [])} variants")
    return "\n".join(lines) + "\n"


def render_merged_ontology(
    merged_classes_json: str,
    output_dir: str,
    python_filename: str = "merged_ontology.py",
    report_filename: str = "alignment_report.md",
    compile_check: bool = True,
) -> dict[str, Any]:
    """Write merged ontology Python and Markdown report files."""

    classes, conflicts = _load_merged_classes(merged_classes_json)
    out_dir = ensure_output_dir(output_dir)
    py_path = out_dir / python_filename
    report_path = out_dir / report_filename
    py_path.write_text(render_python(classes), encoding="utf-8")
    report_path.write_text(render_report(classes, conflicts), encoding="utf-8")

    compile_result: dict[str, Any] | None = None
    if compile_check:
        try:
            py_compile.compile(str(py_path), doraise=True)
            compile_result = {"file": str(py_path), "ok": True}
        except Exception as exc:
            compile_result = {"file": str(py_path), "ok": False, "error": f"{type(exc).__name__}: {exc}"}

    return {
        "output_dir": str(out_dir),
        "python_file": str(py_path),
        "report_file": str(report_path),
        "class_count": len(classes),
        "conflict_count": len(conflicts),
        "compile_result": compile_result,
    }


def render_merged_ontology_json(**kwargs: Any) -> str:
    return json.dumps(render_merged_ontology(**kwargs), ensure_ascii=False, indent=2)
